#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init

prepare_service
SERVICE_NAME="coredns"

coredns_bootstrap_filesystem logs
coredns_bootstrap_filesystem coredns
coredns_configure_coredns

liftoff

