#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init

SERVICE_NAME="coredns"
prepare_service
check_container_initialized

liftoff

case "${LOG_TYPE,,}" in
    both )
        SHOW_OUTPUT=TRUE
        touch "${LOG_PATH%/}"/"${LOG_FILE}"
        chown -R "${COREDNS_USER}" "${LOG_PATH%/}"/"${LOG_FILE}"
    ;;
    console )
        SHOW_OUTPUT=TRUE
        LOG_PATH=/dev
        LOG_FILE=/null
    ;;
    file )
        SHOW_OUTPUT=FALSE
        touch "${LOG_PATH%/}"/"${LOG_FILE}"
        chown -R "${COREDNS_USER}" "${LOG_PATH%/}"/"${LOG_FILE}"
    ;;
    none )
        SHOW_OUTPUT=FALSE
        LOG_PATH=/dev
        LOG_FILE=null
    ;;
esac

print_start "Starting CoreDNS $(coredns -version | head -n1 | cut -d - -f 2)"
export GOMAXPROCS=${MAX_CPUS}
exec s6-setuidgid "${COREDNS_USER}" coredns \
                                     -conf ${CONFIG_PATH}/${CONFIG_FILE} | ts -m '%Y-%m-%dT%H:%M.%S' | silent sudo -u ${COREDNS_USER} tee -a ${LOG_PATH}/${LOG_FILE}
